/// Product vocabulary catalog.
///
/// This catalog is intentionally separate from the 15 E4 detector labels.
/// Detector labels are stable model IDs; catalog entries can grow, be versioned
/// and be downloaded without changing the ONNX model.
class CatalogWord {
  final String id;
  final String english;
  final String vietnamese;
  final String topic;
  final String partOfSpeech;
  final String exampleEnglish;
  final String exampleVietnamese;
  final String source;

  /// Optional provenance fields populated by a published remote release.
  /// Entries without verified publication metadata leave these null; the UI
  /// must never invent an image, source attribution or reviewer record.
  final String? sourceUrl;
  final String? sourceLicense;
  final String? sourceAttribution;
  final String? reviewedBy;
  final String? reviewerType;
  final String? reviewerId;
  final String? reviewedAt;
  final String? imageUrl;
  final String? imageLicense;
  final String? imageAttribution;

  /// Absolute path of a verified file in the local catalog media cache.
  /// Remote [imageUrl] remains the provenance URL and is never overwritten.
  final String? localImagePath;

  const CatalogWord({
    required this.id,
    required this.english,
    required this.vietnamese,
    required this.topic,
    required this.partOfSpeech,
    required this.exampleEnglish,
    required this.exampleVietnamese,
    this.source = 'Vocab Vision editorial starter',
    this.sourceUrl,
    this.sourceLicense,
    this.sourceAttribution,
    this.reviewedBy,
    this.reviewerType,
    this.reviewerId,
    this.reviewedAt,
    this.imageUrl,
    this.imageLicense,
    this.imageAttribution,
    this.localImagePath,
  });

  CatalogWord copyWith({String? localImagePath}) => CatalogWord(
    id: id,
    english: english,
    vietnamese: vietnamese,
    topic: topic,
    partOfSpeech: partOfSpeech,
    exampleEnglish: exampleEnglish,
    exampleVietnamese: exampleVietnamese,
    source: source,
    sourceUrl: sourceUrl,
    sourceLicense: sourceLicense,
    sourceAttribution: sourceAttribution,
    reviewedBy: reviewedBy,
    reviewerType: reviewerType,
    reviewerId: reviewerId,
    reviewedAt: reviewedAt,
    imageUrl: imageUrl,
    imageLicense: imageLicense,
    imageAttribution: imageAttribution,
    localImagePath: localImagePath ?? this.localImagePath,
  );

  CatalogWord withoutLocalImagePath() => CatalogWord(
    id: id,
    english: english,
    vietnamese: vietnamese,
    topic: topic,
    partOfSpeech: partOfSpeech,
    exampleEnglish: exampleEnglish,
    exampleVietnamese: exampleVietnamese,
    source: source,
    sourceUrl: sourceUrl,
    sourceLicense: sourceLicense,
    sourceAttribution: sourceAttribution,
    reviewedBy: reviewedBy,
    reviewerType: reviewerType,
    reviewerId: reviewerId,
    reviewedAt: reviewedAt,
    imageUrl: imageUrl,
    imageLicense: imageLicense,
    imageAttribution: imageAttribution,
  );

  bool get hasOfflineImage {
    final local = localImagePath?.trim();
    final url = imageUrl?.trim();
    return (local != null && local.isNotEmpty) ||
        (url != null && url.startsWith('assets/'));
  }
}

/// Bump this only when the bundled starter content itself changes. A
/// downloaded/remote release is never replaced by this fallback.
const starterCatalogReleaseVersion = 'starter-2026-09-media3';

CatalogWord _starterWord(
  String id,
  String english,
  String vietnamese,
  String topic,
  String partOfSpeech,
  String exampleEnglish,
  String exampleVietnamese,
) => CatalogWord(
  id: id,
  english: english,
  vietnamese: vietnamese,
  topic: topic,
  partOfSpeech: partOfSpeech,
  exampleEnglish: exampleEnglish,
  exampleVietnamese: exampleVietnamese,
);

/// Text-only starter expansion. These entries intentionally do not claim
/// licensed media or production publication; the release pipeline adds source,
/// examples and review records before a remote pack can publish them.
final _expandedStarterWords = <CatalogWord>[
  _starterWord(
    'one',
    'One',
    'Một',
    'Số đếm',
    'number',
    'I have one book.',
    'Em có một quyển sách.',
  ),
  _starterWord(
    'ten',
    'Ten',
    'Mười',
    'Số đếm',
    'number',
    'Ten fingers make two hands.',
    'Mười ngón tay tạo thành hai bàn tay.',
  ),
  _starterWord(
    'circle',
    'Circle',
    'Hình tròn',
    'Hình dạng',
    'noun',
    'The clock is a circle.',
    'Chiếc đồng hồ có hình tròn.',
  ),
  _starterWord(
    'square',
    'Square',
    'Hình vuông',
    'Hình dạng',
    'noun',
    'Draw a square on the paper.',
    'Hãy vẽ một hình vuông trên giấy.',
  ),
  _starterWord(
    'head',
    'Head',
    'Đầu',
    'Cơ thể',
    'noun',
    'Touch your head.',
    'Hãy chạm vào đầu của em.',
  ),
  _starterWord(
    'hand',
    'Hand',
    'Bàn tay',
    'Cơ thể',
    'noun',
    'Raise your hand.',
    'Hãy giơ bàn tay lên.',
  ),
  _starterWord(
    'wake',
    'Wake up',
    'Thức dậy',
    'Hành động hằng ngày',
    'verb',
    'I wake up early.',
    'Em thức dậy sớm.',
  ),
  _starterWord(
    'brush',
    'Brush',
    'Chải',
    'Hành động hằng ngày',
    'verb',
    'I brush my teeth.',
    'Em chải răng.',
  ),
  _starterWord(
    'table',
    'Table',
    'Cái bàn',
    'Đồ trong nhà',
    'noun',
    'The cup is on the table.',
    'Cái cốc ở trên bàn.',
  ),
  _starterWord(
    'chair',
    'Chair',
    'Cái ghế',
    'Đồ trong nhà',
    'noun',
    'Please sit on the chair.',
    'Hãy ngồi lên ghế.',
  ),
  _starterWord(
    'plate',
    'Plate',
    'Đĩa',
    'Phòng bếp',
    'noun',
    'The plate is clean.',
    'Cái đĩa sạch.',
  ),
  _starterWord(
    'spoon',
    'Spoon',
    'Thìa',
    'Phòng bếp',
    'noun',
    'I eat soup with a spoon.',
    'Em ăn súp bằng thìa.',
  ),
  _starterWord(
    'bed',
    'Bed',
    'Giường',
    'Phòng ngủ',
    'noun',
    'The toy is on the bed.',
    'Đồ chơi ở trên giường.',
  ),
  _starterWord(
    'pillow',
    'Pillow',
    'Gối',
    'Phòng ngủ',
    'noun',
    'My pillow is soft.',
    'Cái gối của em mềm.',
  ),
  _starterWord(
    'shirt',
    'Shirt',
    'Áo sơ mi',
    'Quần áo',
    'noun',
    'His shirt is blue.',
    'Áo của bạn ấy màu xanh.',
  ),
  _starterWord(
    'dress',
    'Dress',
    'Váy',
    'Quần áo',
    'noun',
    'She wears a red dress.',
    'Bạn ấy mặc một chiếc váy đỏ.',
  ),
  _starterWord(
    'shoe',
    'Shoe',
    'Giày',
    'Giày và phụ kiện',
    'noun',
    'My shoe is under the chair.',
    'Chiếc giày của em ở dưới ghế.',
  ),
  _starterWord(
    'hat',
    'Hat',
    'Mũ',
    'Giày và phụ kiện',
    'noun',
    'Put on your hat.',
    'Hãy đội mũ vào.',
  ),
  _starterWord(
    'rice',
    'Rice',
    'Cơm',
    'Món ăn',
    'noun',
    'We eat rice for lunch.',
    'Chúng em ăn cơm trưa.',
  ),
  _starterWord(
    'bread',
    'Bread',
    'Bánh mì',
    'Món ăn',
    'noun',
    'The bread is warm.',
    'Bánh mì còn ấm.',
  ),
  _starterWord(
    'water',
    'Water',
    'Nước',
    'Đồ uống',
    'noun',
    'Drink some water.',
    'Hãy uống một ít nước.',
  ),
  _starterWord(
    'milk',
    'Milk',
    'Sữa',
    'Đồ uống',
    'noun',
    'The child drinks milk.',
    'Bạn nhỏ uống sữa.',
  ),
  _starterWord(
    'hamster',
    'Hamster',
    'Chuột hamster',
    'Thú nuôi',
    'noun',
    'The hamster runs in its wheel.',
    'Chuột hamster chạy trong bánh xe.',
  ),
  _starterWord(
    'turtle',
    'Turtle',
    'Rùa',
    'Thú nuôi',
    'noun',
    'The turtle moves slowly.',
    'Con rùa di chuyển chậm.',
  ),
  _starterWord(
    'tiger',
    'Tiger',
    'Hổ',
    'Động vật hoang dã',
    'noun',
    'The tiger has stripes.',
    'Con hổ có các sọc.',
  ),
  _starterWord(
    'elephant',
    'Elephant',
    'Voi',
    'Động vật hoang dã',
    'noun',
    'The elephant has a long trunk.',
    'Con voi có chiếc vòi dài.',
  ),
  _starterWord(
    'eagle',
    'Eagle',
    'Đại bàng',
    'Chim',
    'noun',
    'An eagle flies high.',
    'Một con đại bàng bay cao.',
  ),
  _starterWord(
    'parrot',
    'Parrot',
    'Vẹt',
    'Chim',
    'noun',
    'The parrot is green.',
    'Con vẹt màu xanh lá.',
  ),
  _starterWord(
    'whale',
    'Whale',
    'Cá voi',
    'Sinh vật biển',
    'noun',
    'The whale lives in the ocean.',
    'Cá voi sống trong đại dương.',
  ),
  _starterWord(
    'dolphin',
    'Dolphin',
    'Cá heo',
    'Sinh vật biển',
    'noun',
    'The dolphin jumps out of the water.',
    'Cá heo nhảy khỏi mặt nước.',
  ),
  _starterWord(
    'ant',
    'Ant',
    'Con kiến',
    'Côn trùng',
    'noun',
    'The ant carries a crumb.',
    'Con kiến tha một mẩu thức ăn.',
  ),
  _starterWord(
    'butterfly',
    'Butterfly',
    'Bướm',
    'Côn trùng',
    'noun',
    'A butterfly lands on the flower.',
    'Một con bướm đậu trên hoa.',
  ),
  _starterWord(
    'tree',
    'Tree',
    'Cây',
    'Cây và hoa',
    'noun',
    'The tree gives us shade.',
    'Cây cho chúng ta bóng mát.',
  ),
  _starterWord(
    'flower',
    'Flower',
    'Bông hoa',
    'Cây và hoa',
    'noun',
    'This flower smells sweet.',
    'Bông hoa này có mùi thơm.',
  ),
  _starterWord(
    'sunny',
    'Sunny',
    'Có nắng',
    'Thời tiết',
    'adjective',
    'It is sunny today.',
    'Hôm nay trời có nắng.',
  ),
  _starterWord(
    'rainy',
    'Rainy',
    'Có mưa',
    'Thời tiết',
    'adjective',
    'A rainy day is cool.',
    'Ngày mưa thì mát.',
  ),
  _starterWord(
    'spring',
    'Spring',
    'Mùa xuân',
    'Mùa',
    'noun',
    'Flowers bloom in spring.',
    'Hoa nở vào mùa xuân.',
  ),
  _starterWord(
    'winter',
    'Winter',
    'Mùa đông',
    'Mùa',
    'noun',
    'Winter nights are long.',
    'Đêm mùa đông dài.',
  ),
  _starterWord(
    'morning',
    'Morning',
    'Buổi sáng',
    'Thời gian',
    'noun',
    'Good morning, teacher.',
    'Chào buổi sáng, cô giáo.',
  ),
  _starterWord(
    'night',
    'Night',
    'Ban đêm',
    'Thời gian',
    'noun',
    'The stars shine at night.',
    'Các vì sao tỏa sáng ban đêm.',
  ),
  _starterWord(
    'monday',
    'Monday',
    'Thứ hai',
    'Ngày và tháng',
    'noun',
    'School starts on Monday.',
    'Trường học bắt đầu vào thứ hai.',
  ),
  _starterWord(
    'january',
    'January',
    'Tháng một',
    'Ngày và tháng',
    'noun',
    'January is the first month.',
    'Tháng một là tháng đầu tiên.',
  ),
  _starterWord(
    'bus',
    'Bus',
    'Xe buýt',
    'Phương tiện',
    'noun',
    'I go to school by bus.',
    'Em đi học bằng xe buýt.',
  ),
  _starterWord(
    'bicycle',
    'Bicycle',
    'Xe đạp',
    'Phương tiện',
    'noun',
    'She rides a bicycle.',
    'Bạn ấy đi xe đạp.',
  ),
  _starterWord(
    'bridge',
    'Bridge',
    'Cây cầu',
    'Đường phố',
    'noun',
    'The bridge crosses the river.',
    'Cây cầu bắc qua sông.',
  ),
  _starterWord(
    'traffic_light',
    'Traffic light',
    'Đèn giao thông',
    'Đường phố',
    'noun',
    'Stop at the red traffic light.',
    'Dừng lại khi đèn giao thông màu đỏ.',
  ),
  _starterWord(
    'doctor',
    'Doctor',
    'Bác sĩ',
    'Nghề nghiệp',
    'noun',
    'The doctor helps sick people.',
    'Bác sĩ giúp người bệnh.',
  ),
  _starterWord(
    'teacher',
    'Teacher',
    'Giáo viên',
    'Nghề nghiệp',
    'noun',
    'The teacher reads a story.',
    'Giáo viên đọc một câu chuyện.',
  ),
  _starterWord(
    'football',
    'Football',
    'Bóng đá',
    'Thể thao',
    'noun',
    'We play football after class.',
    'Chúng em chơi bóng đá sau giờ học.',
  ),
  _starterWord(
    'swimming',
    'Swimming',
    'Bơi lội',
    'Thể thao',
    'noun',
    'Swimming is good exercise.',
    'Bơi lội là bài tập tốt.',
  ),
  _starterWord(
    'drawing',
    'Drawing',
    'Vẽ tranh',
    'Sở thích',
    'noun',
    'Drawing is my hobby.',
    'Vẽ tranh là sở thích của em.',
  ),
  _starterWord(
    'music',
    'Music',
    'Âm nhạc',
    'Sở thích',
    'noun',
    'I listen to music at home.',
    'Em nghe nhạc ở nhà.',
  ),
  _starterWord(
    'doll',
    'Doll',
    'Búp bê',
    'Đồ chơi',
    'noun',
    'The doll has a yellow dress.',
    'Búp bê mặc váy màu vàng.',
  ),
  _starterWord(
    'ball',
    'Ball',
    'Quả bóng',
    'Đồ chơi',
    'noun',
    'The ball rolls on the floor.',
    'Quả bóng lăn trên sàn.',
  ),
  _starterWord(
    'piano',
    'Piano',
    'Đàn piano',
    'Nhạc cụ',
    'noun',
    'She plays the piano.',
    'Bạn ấy chơi đàn piano.',
  ),
  _starterWord(
    'guitar',
    'Guitar',
    'Đàn ghi-ta',
    'Nhạc cụ',
    'noun',
    'My brother has a guitar.',
    'Anh của em có một cây ghi-ta.',
  ),
  _starterWord(
    'computer',
    'Computer',
    'Máy tính',
    'Công nghệ',
    'noun',
    'The computer is on the desk.',
    'Máy tính ở trên bàn.',
  ),
  _starterWord(
    'tablet',
    'Tablet',
    'Máy tính bảng',
    'Công nghệ',
    'noun',
    'I read on a tablet.',
    'Em đọc sách trên máy tính bảng.',
  ),
  _starterWord(
    'river',
    'River',
    'Dòng sông',
    'Thiên nhiên',
    'noun',
    'The river is wide.',
    'Dòng sông rộng.',
  ),
  _starterWord(
    'mountain',
    'Mountain',
    'Ngọn núi',
    'Thiên nhiên',
    'noun',
    'The mountain is high.',
    'Ngọn núi cao.',
  ),
  _starterWord(
    'airport',
    'Airport',
    'Sân bay',
    'Du lịch',
    'noun',
    'We arrive at the airport early.',
    'Chúng em đến sân bay sớm.',
  ),
  _starterWord(
    'hotel',
    'Hotel',
    'Khách sạn',
    'Du lịch',
    'noun',
    'The hotel has a small pool.',
    'Khách sạn có một hồ bơi nhỏ.',
  ),
];

/// A second editorial tranche keeps the offline demo useful beyond the E4
/// object labels. These records deliberately remain bundled starter content:
/// they have bilingual examples but no publication/reviewer metadata, so the
/// release pipeline must still review and source them before serving them as a
/// production catalog pack.
CatalogWord _curatedWord(
  String id,
  String english,
  String vietnamese,
  String topic,
  String partOfSpeech,
  String exampleEnglish,
  String exampleVietnamese,
) => CatalogWord(
  id: id,
  english: english,
  vietnamese: vietnamese,
  topic: topic,
  partOfSpeech: partOfSpeech,
  exampleEnglish: exampleEnglish,
  exampleVietnamese: exampleVietnamese,
  source: 'Vocab Vision editorial starter 2026',
);

final _curatedStarterExpansion = <CatalogWord>[
  _curatedWord(
    'folder',
    'Folder',
    'Bìa hồ sơ',
    'Đồ dùng học tập',
    'noun',
    'Keep the worksheet in the folder.',
    'Hãy để bài tập trong bìa hồ sơ.',
  ),
  _curatedWord(
    'marker',
    'Marker',
    'Bút dạ',
    'Đồ dùng học tập',
    'noun',
    'Use a marker to underline the title.',
    'Dùng bút dạ để gạch chân tiêu đề.',
  ),
  _curatedWord(
    'stapler',
    'Stapler',
    'Dập ghim',
    'Đồ dùng học tập',
    'noun',
    'The stapler is beside the printer.',
    'Dụng cụ dập ghim ở cạnh máy in.',
  ),
  _curatedWord(
    'calculator',
    'Calculator',
    'Máy tính',
    'Đồ dùng học tập',
    'noun',
    'I use a calculator for this problem.',
    'Em dùng máy tính cho bài toán này.',
  ),
  _curatedWord(
    'globe',
    'Globe',
    'Quả địa cầu',
    'Đồ dùng học tập',
    'noun',
    'The globe shows many countries.',
    'Quả địa cầu có nhiều quốc gia.',
  ),

  _curatedWord(
    'mango',
    'Mango',
    'Quả xoài',
    'Trái cây',
    'noun',
    'The mango is soft and sweet.',
    'Quả xoài mềm và ngọt.',
  ),
  _curatedWord(
    'pear',
    'Pear',
    'Quả lê',
    'Trái cây',
    'noun',
    'The pear is on the plate.',
    'Quả lê ở trên đĩa.',
  ),
  _curatedWord(
    'peach',
    'Peach',
    'Quả đào',
    'Trái cây',
    'noun',
    'She cuts a peach for lunch.',
    'Bạn ấy cắt một quả đào cho bữa trưa.',
  ),
  _curatedWord(
    'strawberry',
    'Strawberry',
    'Quả dâu tây',
    'Trái cây',
    'noun',
    'The strawberry is bright red.',
    'Quả dâu tây có màu đỏ tươi.',
  ),
  _curatedWord(
    'coconut',
    'Coconut',
    'Quả dừa',
    'Trái cây',
    'noun',
    'We drink coconut water.',
    'Chúng em uống nước dừa.',
  ),

  _curatedWord(
    'onion',
    'Onion',
    'Củ hành tây',
    'Rau củ',
    'noun',
    'The onion is in the basket.',
    'Củ hành tây ở trong giỏ.',
  ),
  _curatedWord(
    'cucumber',
    'Cucumber',
    'Dưa chuột',
    'Rau củ',
    'noun',
    'Slice the cucumber thinly.',
    'Hãy thái dưa chuột thành lát mỏng.',
  ),
  _curatedWord(
    'cabbage',
    'Cabbage',
    'Bắp cải',
    'Rau củ',
    'noun',
    'The cabbage grows in the garden.',
    'Bắp cải mọc trong vườn.',
  ),
  _curatedWord(
    'corn',
    'Corn',
    'Ngô',
    'Rau củ',
    'noun',
    'The corn is yellow and fresh.',
    'Bắp ngô màu vàng và tươi.',
  ),
  _curatedWord(
    'pumpkin',
    'Pumpkin',
    'Bí ngô',
    'Rau củ',
    'noun',
    'We cook pumpkin soup.',
    'Chúng em nấu súp bí ngô.',
  ),

  _curatedWord(
    'lion',
    'Lion',
    'Sư tử',
    'Động vật',
    'noun',
    'The lion rests under a tree.',
    'Sư tử nghỉ dưới một cái cây.',
  ),
  _curatedWord(
    'bear',
    'Bear',
    'Con gấu',
    'Động vật',
    'noun',
    'The bear has thick fur.',
    'Con gấu có bộ lông dày.',
  ),
  _curatedWord(
    'monkey',
    'Monkey',
    'Con khỉ',
    'Động vật',
    'noun',
    'The monkey climbs the tree.',
    'Con khỉ trèo lên cây.',
  ),
  _curatedWord(
    'horse',
    'Horse',
    'Con ngựa',
    'Động vật',
    'noun',
    'The horse runs across the field.',
    'Con ngựa chạy qua cánh đồng.',
  ),
  _curatedWord(
    'cow',
    'Cow',
    'Con bò',
    'Động vật',
    'noun',
    'The cow eats grass.',
    'Con bò ăn cỏ.',
  ),
  _curatedWord(
    'goat',
    'Goat',
    'Con dê',
    'Động vật',
    'noun',
    'The goat stands on the hill.',
    'Con dê đứng trên ngọn đồi.',
  ),

  _curatedWord(
    'grandmother',
    'Grandmother',
    'Bà',
    'Gia đình',
    'noun',
    'My grandmother tells funny stories.',
    'Bà kể những câu chuyện vui.',
  ),
  _curatedWord(
    'grandfather',
    'Grandfather',
    'Ông',
    'Gia đình',
    'noun',
    'My grandfather grows flowers.',
    'Ông trồng hoa.',
  ),
  _curatedWord(
    'cousin',
    'Cousin',
    'Anh chị em họ',
    'Gia đình',
    'noun',
    'My cousin visits us on Sunday.',
    'Anh chị em họ đến thăm chúng em vào Chủ nhật.',
  ),
  _curatedWord(
    'baby',
    'Baby',
    'Em bé',
    'Gia đình',
    'noun',
    'The baby is smiling.',
    'Em bé đang mỉm cười.',
  ),

  _curatedWord(
    'park',
    'Park',
    'Công viên',
    'Địa điểm',
    'noun',
    'The children play in the park.',
    'Các bạn nhỏ chơi trong công viên.',
  ),
  _curatedWord(
    'hospital',
    'Hospital',
    'Bệnh viện',
    'Địa điểm',
    'noun',
    'The hospital is near our school.',
    'Bệnh viện ở gần trường em.',
  ),
  _curatedWord(
    'museum',
    'Museum',
    'Bảo tàng',
    'Địa điểm',
    'noun',
    'We learn about history at the museum.',
    'Chúng em tìm hiểu lịch sử ở bảo tàng.',
  ),
  _curatedWord(
    'market',
    'Market',
    'Chợ',
    'Địa điểm',
    'noun',
    'Dad buys fruit at the market.',
    'Bố mua trái cây ở chợ.',
  ),

  _curatedWord(
    'black',
    'Black',
    'Màu đen',
    'Màu sắc',
    'adjective',
    'The black cat sits by the door.',
    'Con mèo đen ngồi cạnh cửa.',
  ),
  _curatedWord(
    'white',
    'White',
    'Màu trắng',
    'Màu sắc',
    'adjective',
    'The cloud is white.',
    'Đám mây màu trắng.',
  ),
  _curatedWord(
    'pink',
    'Pink',
    'Màu hồng',
    'Màu sắc',
    'adjective',
    'She has a pink pencil case.',
    'Bạn ấy có một hộp bút màu hồng.',
  ),
  _curatedWord(
    'purple',
    'Purple',
    'Màu tím',
    'Màu sắc',
    'adjective',
    'The purple flower is beautiful.',
    'Bông hoa màu tím rất đẹp.',
  ),

  _curatedWord(
    'jump',
    'Jump',
    'Nhảy',
    'Hành động',
    'verb',
    'Can you jump over the line?',
    'Em có thể nhảy qua vạch không?',
  ),
  _curatedWord(
    'sit',
    'Sit',
    'Ngồi',
    'Hành động',
    'verb',
    'Please sit on the chair.',
    'Hãy ngồi trên ghế.',
  ),
  _curatedWord(
    'stand',
    'Stand',
    'Đứng',
    'Hành động',
    'verb',
    'Please stand in a line.',
    'Hãy đứng thành hàng.',
  ),
  _curatedWord(
    'open',
    'Open',
    'Mở',
    'Hành động',
    'verb',
    'Open your book to page five.',
    'Mở sách ở trang năm.',
  ),
  _curatedWord(
    'close',
    'Close',
    'Đóng',
    'Hành động',
    'verb',
    'Close the door quietly.',
    'Hãy đóng cửa nhẹ nhàng.',
  ),

  _curatedWord(
    'sad',
    'Sad',
    'Buồn',
    'Cảm xúc',
    'adjective',
    'He feels sad after losing the game.',
    'Bạn ấy buồn sau khi thua trận.',
  ),
  _curatedWord(
    'angry',
    'Angry',
    'Tức giận',
    'Cảm xúc',
    'adjective',
    'She is angry about the broken toy.',
    'Bạn ấy tức giận vì món đồ chơi bị hỏng.',
  ),
  _curatedWord(
    'excited',
    'Excited',
    'Hào hứng',
    'Cảm xúc',
    'adjective',
    'We are excited about the trip.',
    'Chúng em hào hứng với chuyến đi.',
  ),
  _curatedWord(
    'scared',
    'Scared',
    'Sợ hãi',
    'Cảm xúc',
    'adjective',
    'The little boy is scared of the thunder.',
    'Cậu bé sợ tiếng sấm.',
  ),
  _curatedWord(
    'calm',
    'Calm',
    'Bình tĩnh',
    'Cảm xúc',
    'adjective',
    'Take a breath and stay calm.',
    'Hãy hít thở và giữ bình tĩnh.',
  ),
  _curatedWord(
    'proud',
    'Proud',
    'Tự hào',
    'Cảm xúc',
    'adjective',
    'I am proud of your good work.',
    'Em tự hào về bài làm tốt của anh.',
  ),

  _curatedWord(
    'two',
    'Two',
    'Hai',
    'Số đếm',
    'number',
    'I have two pencils.',
    'Em có hai chiếc bút chì.',
  ),
  _curatedWord(
    'three',
    'Three',
    'Ba',
    'Số đếm',
    'number',
    'There are three books here.',
    'Có ba quyển sách ở đây.',
  ),
  _curatedWord(
    'four',
    'Four',
    'Bốn',
    'Số đếm',
    'number',
    'Four birds sit on the wall.',
    'Bốn con chim đậu trên tường.',
  ),
  _curatedWord(
    'five',
    'Five',
    'Năm',
    'Số đếm',
    'number',
    'The hand has five fingers.',
    'Bàn tay có năm ngón.',
  ),
  _curatedWord(
    'six',
    'Six',
    'Sáu',
    'Số đếm',
    'number',
    'Six children share the crayons.',
    'Sáu bạn nhỏ cùng dùng bút sáp.',
  ),

  _curatedWord(
    'triangle',
    'Triangle',
    'Hình tam giác',
    'Hình dạng',
    'noun',
    'The sign is a triangle.',
    'Biển báo có hình tam giác.',
  ),
  _curatedWord(
    'rectangle',
    'Rectangle',
    'Hình chữ nhật',
    'Hình dạng',
    'noun',
    'Draw a rectangle on the page.',
    'Hãy vẽ một hình chữ nhật trên trang giấy.',
  ),
  _curatedWord(
    'oval',
    'Oval',
    'Hình bầu dục',
    'Hình dạng',
    'noun',
    'The egg has an oval shape.',
    'Quả trứng có hình bầu dục.',
  ),
  _curatedWord(
    'star',
    'Star',
    'Ngôi sao',
    'Hình dạng',
    'noun',
    'The sticker is a yellow star.',
    'Miếng dán là một ngôi sao vàng.',
  ),
  _curatedWord(
    'heart',
    'Heart',
    'Trái tim',
    'Hình dạng',
    'noun',
    'Draw a heart for your card.',
    'Hãy vẽ một trái tim cho tấm thiệp.',
  ),

  _curatedWord(
    'eye',
    'Eye',
    'Mắt',
    'Cơ thể',
    'noun',
    'Close one eye.',
    'Hãy nhắm một mắt.',
  ),
  _curatedWord(
    'ear',
    'Ear',
    'Tai',
    'Cơ thể',
    'noun',
    'My ear can hear the music.',
    'Tai của em nghe được tiếng nhạc.',
  ),
  _curatedWord(
    'nose',
    'Nose',
    'Mũi',
    'Cơ thể',
    'noun',
    'The nose can smell flowers.',
    'Mũi có thể ngửi mùi hoa.',
  ),
  _curatedWord(
    'mouth',
    'Mouth',
    'Miệng',
    'Cơ thể',
    'noun',
    'Open your mouth wide.',
    'Hãy mở miệng thật rộng.',
  ),
  _curatedWord(
    'foot',
    'Foot',
    'Bàn chân',
    'Cơ thể',
    'noun',
    'My foot is inside the shoe.',
    'Bàn chân của em ở trong giày.',
  ),

  _curatedWord(
    'brush_teeth',
    'Brush teeth',
    'Đánh răng',
    'Hành động hằng ngày',
    'verb',
    'I brush my teeth every morning.',
    'Em đánh răng mỗi sáng.',
  ),
  _curatedWord(
    'eat',
    'Eat',
    'Ăn',
    'Hành động hằng ngày',
    'verb',
    'We eat breakfast at seven.',
    'Chúng em ăn sáng lúc bảy giờ.',
  ),
  _curatedWord(
    'drink',
    'Drink',
    'Uống',
    'Hành động hằng ngày',
    'verb',
    'Remember to drink enough water.',
    'Hãy nhớ uống đủ nước.',
  ),
  _curatedWord(
    'sleep',
    'Sleep',
    'Ngủ',
    'Hành động hằng ngày',
    'verb',
    'Children need to sleep early.',
    'Trẻ em cần ngủ sớm.',
  ),
  _curatedWord(
    'wash',
    'Wash',
    'Rửa',
    'Hành động hằng ngày',
    'verb',
    'Wash your hands before lunch.',
    'Hãy rửa tay trước bữa trưa.',
  ),

  _curatedWord(
    'sofa',
    'Sofa',
    'Ghế sofa',
    'Đồ trong nhà',
    'noun',
    'The sofa is in the living room.',
    'Ghế sofa ở trong phòng khách.',
  ),
  _curatedWord(
    'door',
    'Door',
    'Cửa ra vào',
    'Đồ trong nhà',
    'noun',
    'Please open the door.',
    'Hãy mở cửa ra vào.',
  ),
  _curatedWord(
    'window',
    'Window',
    'Cửa sổ',
    'Đồ trong nhà',
    'noun',
    'The window lets in sunlight.',
    'Cửa sổ để ánh nắng chiếu vào.',
  ),
  _curatedWord(
    'lamp',
    'Lamp',
    'Đèn',
    'Đồ trong nhà',
    'noun',
    'Turn on the lamp at night.',
    'Hãy bật đèn vào ban đêm.',
  ),
  _curatedWord(
    'clock',
    'Clock',
    'Đồng hồ',
    'Đồ trong nhà',
    'noun',
    'The clock is above the desk.',
    'Đồng hồ ở phía trên bàn.',
  ),

  _curatedWord(
    'pan',
    'Pan',
    'Chảo',
    'Phòng bếp',
    'noun',
    'The eggs are in the pan.',
    'Trứng ở trong chảo.',
  ),
  _curatedWord(
    'pot',
    'Pot',
    'Nồi',
    'Phòng bếp',
    'noun',
    'The soup is hot in the pot.',
    'Súp nóng ở trong nồi.',
  ),
  _curatedWord(
    'bowl',
    'Bowl',
    'Bát',
    'Phòng bếp',
    'noun',
    'Put the rice in the bowl.',
    'Cho cơm vào bát.',
  ),
  _curatedWord(
    'knife',
    'Knife',
    'Dao',
    'Phòng bếp',
    'noun',
    'Use the knife carefully.',
    'Hãy dùng dao cẩn thận.',
  ),
  _curatedWord(
    'fridge',
    'Fridge',
    'Tủ lạnh',
    'Phòng bếp',
    'noun',
    'The milk is in the fridge.',
    'Sữa ở trong tủ lạnh.',
  ),

  _curatedWord(
    'blanket',
    'Blanket',
    'Chăn',
    'Phòng ngủ',
    'noun',
    'The blanket keeps me warm.',
    'Chăn giữ ấm cho em.',
  ),
  _curatedWord(
    'desk',
    'Desk',
    'Bàn học',
    'Phòng ngủ',
    'noun',
    'My books are on the desk.',
    'Sách của em ở trên bàn học.',
  ),
  _curatedWord(
    'wardrobe',
    'Wardrobe',
    'Tủ quần áo',
    'Phòng ngủ',
    'noun',
    'The coat is in the wardrobe.',
    'Áo khoác ở trong tủ quần áo.',
  ),
  _curatedWord(
    'mirror',
    'Mirror',
    'Gương',
    'Phòng ngủ',
    'noun',
    'Look in the mirror.',
    'Hãy nhìn vào gương.',
  ),
  _curatedWord(
    'alarm_clock',
    'Alarm clock',
    'Đồng hồ báo thức',
    'Phòng ngủ',
    'noun',
    'My alarm clock rings at six.',
    'Đồng hồ báo thức reo lúc sáu giờ.',
  ),

  _curatedWord(
    'pants',
    'Pants',
    'Quần dài',
    'Quần áo',
    'noun',
    'These pants are comfortable.',
    'Chiếc quần dài này rất thoải mái.',
  ),
  _curatedWord(
    'skirt',
    'Skirt',
    'Váy',
    'Quần áo',
    'noun',
    'She wears a blue skirt.',
    'Bạn ấy mặc một chiếc váy xanh.',
  ),
  _curatedWord(
    'socks',
    'Socks',
    'Tất',
    'Quần áo',
    'noun',
    'My socks are clean.',
    'Tất của em sạch.',
  ),
  _curatedWord(
    'coat',
    'Coat',
    'Áo khoác',
    'Quần áo',
    'noun',
    'Wear a coat on a cold day.',
    'Hãy mặc áo khoác vào ngày lạnh.',
  ),
  _curatedWord(
    'sweater',
    'Sweater',
    'Áo len',
    'Quần áo',
    'noun',
    'The red sweater is warm.',
    'Chiếc áo len đỏ rất ấm.',
  ),

  _curatedWord(
    'sandals',
    'Sandals',
    'Dép xăng-đan',
    'Giày và phụ kiện',
    'noun',
    'I wear sandals to the beach.',
    'Em đi dép xăng-đan ra biển.',
  ),
  _curatedWord(
    'boots',
    'Boots',
    'Ủng',
    'Giày và phụ kiện',
    'noun',
    'The boots keep my feet dry.',
    'Đôi ủng giữ cho chân em khô.',
  ),
  _curatedWord(
    'belt',
    'Belt',
    'Thắt lưng',
    'Giày và phụ kiện',
    'noun',
    'His belt is brown.',
    'Thắt lưng của bạn ấy màu nâu.',
  ),
  _curatedWord(
    'scarf',
    'Scarf',
    'Khăn quàng',
    'Giày và phụ kiện',
    'noun',
    'She wears a scarf in winter.',
    'Bạn ấy quàng khăn vào mùa đông.',
  ),
  _curatedWord(
    'gloves',
    'Gloves',
    'Găng tay',
    'Giày và phụ kiện',
    'noun',
    'Put on gloves in the snow.',
    'Hãy đeo găng tay khi có tuyết.',
  ),

  _curatedWord(
    'noodles',
    'Noodles',
    'Mì',
    'Món ăn',
    'noun',
    'We eat noodles for breakfast.',
    'Chúng em ăn mì vào bữa sáng.',
  ),
  _curatedWord(
    'soup',
    'Soup',
    'Súp',
    'Món ăn',
    'noun',
    'The soup smells delicious.',
    'Món súp có mùi thơm ngon.',
  ),
  _curatedWord(
    'egg',
    'Egg',
    'Quả trứng',
    'Món ăn',
    'noun',
    'I put an egg on the plate.',
    'Em đặt một quả trứng lên đĩa.',
  ),
  _curatedWord(
    'chicken',
    'Chicken',
    'Thịt gà',
    'Món ăn',
    'noun',
    'The chicken is ready for dinner.',
    'Thịt gà đã sẵn sàng cho bữa tối.',
  ),
  _curatedWord(
    'sandwich',
    'Sandwich',
    'Bánh mì kẹp',
    'Món ăn',
    'noun',
    'Dad makes a sandwich for me.',
    'Bố làm bánh mì kẹp cho em.',
  ),
  _curatedWord(
    'pizza',
    'Pizza',
    'Bánh pizza',
    'Món ăn',
    'noun',
    'The pizza has cheese on top.',
    'Bánh pizza có phô mai ở trên.',
  ),

  _curatedWord(
    'juice',
    'Juice',
    'Nước ép',
    'Đồ uống',
    'noun',
    'She drinks orange juice.',
    'Bạn ấy uống nước cam.',
  ),
  _curatedWord(
    'tea',
    'Tea',
    'Trà',
    'Đồ uống',
    'noun',
    'Grandpa drinks tea every morning.',
    'Ông uống trà mỗi sáng.',
  ),
  _curatedWord(
    'coffee',
    'Coffee',
    'Cà phê',
    'Đồ uống',
    'noun',
    'Mom makes coffee in the kitchen.',
    'Mẹ pha cà phê trong bếp.',
  ),
  _curatedWord(
    'lemonade',
    'Lemonade',
    'Nước chanh',
    'Đồ uống',
    'noun',
    'The lemonade is cold and fresh.',
    'Nước chanh mát và tươi.',
  ),

  _curatedWord(
    'puppy',
    'Puppy',
    'Chó con',
    'Thú nuôi',
    'noun',
    'The puppy plays with a ball.',
    'Chú chó con chơi với quả bóng.',
  ),
  _curatedWord(
    'kitten',
    'Kitten',
    'Mèo con',
    'Thú nuôi',
    'noun',
    'The kitten sleeps in a basket.',
    'Mèo con ngủ trong một chiếc giỏ.',
  ),
  _curatedWord(
    'goldfish',
    'Goldfish',
    'Cá vàng',
    'Thú nuôi',
    'noun',
    'Our goldfish swims in a small tank.',
    'Cá vàng của chúng em bơi trong bể nhỏ.',
  ),
  _curatedWord(
    'guinea_pig',
    'Guinea pig',
    'Chuột lang',
    'Thú nuôi',
    'noun',
    'The guinea pig eats a carrot.',
    'Chuột lang ăn một củ cà rốt.',
  ),

  _curatedWord(
    'giraffe',
    'Giraffe',
    'Hươu cao cổ',
    'Động vật hoang dã',
    'noun',
    'The giraffe has a long neck.',
    'Hươu cao cổ có chiếc cổ dài.',
  ),
  _curatedWord(
    'zebra',
    'Zebra',
    'Ngựa vằn',
    'Động vật hoang dã',
    'noun',
    'The zebra has black and white stripes.',
    'Ngựa vằn có các sọc đen trắng.',
  ),
  _curatedWord(
    'panda',
    'Panda',
    'Gấu trúc',
    'Động vật hoang dã',
    'noun',
    'The panda eats bamboo.',
    'Gấu trúc ăn tre.',
  ),
  _curatedWord(
    'fox',
    'Fox',
    'Con cáo',
    'Động vật hoang dã',
    'noun',
    'The fox walks quietly at night.',
    'Con cáo đi nhẹ nhàng vào ban đêm.',
  ),
  _curatedWord(
    'wolf',
    'Wolf',
    'Con sói',
    'Động vật hoang dã',
    'noun',
    'The wolf lives in the forest.',
    'Con sói sống trong rừng.',
  ),

  _curatedWord(
    'swan',
    'Swan',
    'Thiên nga',
    'Chim',
    'noun',
    'The swan swims on the lake.',
    'Thiên nga bơi trên hồ.',
  ),
  _curatedWord(
    'owl',
    'Owl',
    'Con cú',
    'Chim',
    'noun',
    'The owl can see at night.',
    'Con cú có thể nhìn vào ban đêm.',
  ),
  _curatedWord(
    'pigeon',
    'Pigeon',
    'Chim bồ câu',
    'Chim',
    'noun',
    'A pigeon sits on the roof.',
    'Một con chim bồ câu đậu trên mái nhà.',
  ),
  _curatedWord(
    'rooster',
    'Rooster',
    'Gà trống',
    'Chim',
    'noun',
    'The rooster crows in the morning.',
    'Gà trống gáy vào buổi sáng.',
  ),

  _curatedWord(
    'shark',
    'Shark',
    'Cá mập',
    'Sinh vật biển',
    'noun',
    'The shark swims in deep water.',
    'Cá mập bơi trong vùng nước sâu.',
  ),
  _curatedWord(
    'octopus',
    'Octopus',
    'Bạch tuộc',
    'Sinh vật biển',
    'noun',
    'The octopus has eight arms.',
    'Bạch tuộc có tám xúc tu.',
  ),
  _curatedWord(
    'crab',
    'Crab',
    'Con cua',
    'Sinh vật biển',
    'noun',
    'The crab walks sideways.',
    'Con cua đi ngang.',
  ),
  _curatedWord(
    'seahorse',
    'Seahorse',
    'Cá ngựa',
    'Sinh vật biển',
    'noun',
    'A seahorse is small and gentle.',
    'Cá ngựa nhỏ và hiền.',
  ),

  _curatedWord(
    'bee',
    'Bee',
    'Con ong',
    'Côn trùng',
    'noun',
    'A bee visits the flower.',
    'Một con ong đến thăm bông hoa.',
  ),
  _curatedWord(
    'beetle',
    'Beetle',
    'Bọ cánh cứng',
    'Côn trùng',
    'noun',
    'The beetle crawls under a leaf.',
    'Bọ cánh cứng bò dưới chiếc lá.',
  ),
  _curatedWord(
    'ladybug',
    'Ladybug',
    'Bọ rùa',
    'Côn trùng',
    'noun',
    'The ladybug has red wings.',
    'Bọ rùa có đôi cánh đỏ.',
  ),
  _curatedWord(
    'mosquito',
    'Mosquito',
    'Muỗi',
    'Côn trùng',
    'noun',
    'A mosquito is near the lamp.',
    'Một con muỗi ở gần chiếc đèn.',
  ),
  _curatedWord(
    'grasshopper',
    'Grasshopper',
    'Châu chấu',
    'Côn trùng',
    'noun',
    'The grasshopper jumps over the grass.',
    'Châu chấu nhảy qua bãi cỏ.',
  ),

  _curatedWord(
    'rose',
    'Rose',
    'Hoa hồng',
    'Cây và hoa',
    'noun',
    'The rose smells sweet.',
    'Hoa hồng có mùi thơm ngọt.',
  ),
  _curatedWord(
    'sunflower',
    'Sunflower',
    'Hoa hướng dương',
    'Cây và hoa',
    'noun',
    'The sunflower faces the sun.',
    'Hoa hướng dương hướng về phía mặt trời.',
  ),
  _curatedWord(
    'leaf',
    'Leaf',
    'Lá cây',
    'Cây và hoa',
    'noun',
    'A green leaf falls down.',
    'Một chiếc lá xanh rơi xuống.',
  ),
  _curatedWord(
    'grass',
    'Grass',
    'Cỏ',
    'Cây và hoa',
    'noun',
    'The grass is wet after rain.',
    'Cỏ ướt sau cơn mưa.',
  ),
  _curatedWord(
    'seed',
    'Seed',
    'Hạt giống',
    'Cây và hoa',
    'noun',
    'Plant the seed in the soil.',
    'Hãy gieo hạt giống vào đất.',
  ),

  _curatedWord(
    'cloudy',
    'Cloudy',
    'Nhiều mây',
    'Thời tiết',
    'adjective',
    'It is cloudy this morning.',
    'Sáng nay trời nhiều mây.',
  ),
  _curatedWord(
    'windy',
    'Windy',
    'Nhiều gió',
    'Thời tiết',
    'adjective',
    'It is windy near the sea.',
    'Gần biển trời nhiều gió.',
  ),
  _curatedWord(
    'snowy',
    'Snowy',
    'Có tuyết',
    'Thời tiết',
    'adjective',
    'The road is snowy today.',
    'Hôm nay con đường có tuyết.',
  ),
  _curatedWord(
    'storm',
    'Storm',
    'Cơn bão',
    'Thời tiết',
    'noun',
    'The storm is moving away.',
    'Cơn bão đang đi xa.',
  ),
  _curatedWord(
    'rainbow',
    'Rainbow',
    'Cầu vồng',
    'Thời tiết',
    'noun',
    'A rainbow appears after the rain.',
    'Cầu vồng xuất hiện sau cơn mưa.',
  ),

  _curatedWord(
    'summer',
    'Summer',
    'Mùa hè',
    'Mùa',
    'noun',
    'We swim in summer.',
    'Chúng em bơi vào mùa hè.',
  ),
  _curatedWord(
    'autumn',
    'Autumn',
    'Mùa thu',
    'Mùa',
    'noun',
    'Leaves turn yellow in autumn.',
    'Lá chuyển màu vàng vào mùa thu.',
  ),

  _curatedWord(
    'afternoon',
    'Afternoon',
    'Buổi chiều',
    'Thời gian',
    'noun',
    'We play outside in the afternoon.',
    'Chúng em chơi bên ngoài vào buổi chiều.',
  ),
  _curatedWord(
    'evening',
    'Evening',
    'Buổi tối',
    'Thời gian',
    'noun',
    'I read in the evening.',
    'Em đọc sách vào buổi tối.',
  ),
  _curatedWord(
    'today',
    'Today',
    'Hôm nay',
    'Thời gian',
    'adverb',
    'Today is a sunny day.',
    'Hôm nay là một ngày nắng.',
  ),
  _curatedWord(
    'tomorrow',
    'Tomorrow',
    'Ngày mai',
    'Thời gian',
    'adverb',
    'We will visit grandma tomorrow.',
    'Ngày mai chúng em sẽ thăm bà.',
  ),
  _curatedWord(
    'yesterday',
    'Yesterday',
    'Hôm qua',
    'Thời gian',
    'adverb',
    'Yesterday we stayed at home.',
    'Hôm qua chúng em ở nhà.',
  ),

  _curatedWord(
    'tuesday',
    'Tuesday',
    'Thứ ba',
    'Ngày và tháng',
    'noun',
    'Our music class is on Tuesday.',
    'Lớp âm nhạc của chúng em vào thứ ba.',
  ),
  _curatedWord(
    'wednesday',
    'Wednesday',
    'Thứ tư',
    'Ngày và tháng',
    'noun',
    'The library is quiet on Wednesday.',
    'Thư viện yên tĩnh vào thứ tư.',
  ),
  _curatedWord(
    'thursday',
    'Thursday',
    'Thứ năm',
    'Ngày và tháng',
    'noun',
    'We have art on Thursday.',
    'Chúng em học mỹ thuật vào thứ năm.',
  ),
  _curatedWord(
    'friday',
    'Friday',
    'Thứ sáu',
    'Ngày và tháng',
    'noun',
    'Friday is the last school day.',
    'Thứ sáu là ngày học cuối tuần.',
  ),
  _curatedWord(
    'sunday',
    'Sunday',
    'Chủ nhật',
    'Ngày và tháng',
    'noun',
    'We visit the park on Sunday.',
    'Chúng em đi công viên vào Chủ nhật.',
  ),

  _curatedWord(
    'car',
    'Car',
    'Ô tô',
    'Phương tiện',
    'noun',
    'The car stops at the light.',
    'Ô tô dừng ở đèn giao thông.',
  ),
  _curatedWord(
    'train',
    'Train',
    'Tàu hỏa',
    'Phương tiện',
    'noun',
    'The train arrives on time.',
    'Tàu hỏa đến đúng giờ.',
  ),
  _curatedWord(
    'plane',
    'Plane',
    'Máy bay',
    'Phương tiện',
    'noun',
    'The plane flies above the clouds.',
    'Máy bay bay trên những đám mây.',
  ),
  _curatedWord(
    'boat',
    'Boat',
    'Thuyền',
    'Phương tiện',
    'noun',
    'The boat is on the river.',
    'Thuyền ở trên sông.',
  ),
  _curatedWord(
    'taxi',
    'Taxi',
    'Xe taxi',
    'Phương tiện',
    'noun',
    'We take a taxi to the station.',
    'Chúng em đi taxi đến nhà ga.',
  ),

  _curatedWord(
    'road',
    'Road',
    'Con đường',
    'Đường phố',
    'noun',
    'The road is busy in the morning.',
    'Con đường đông vào buổi sáng.',
  ),
  _curatedWord(
    'sidewalk',
    'Sidewalk',
    'Vỉa hè',
    'Đường phố',
    'noun',
    'Walk on the sidewalk, please.',
    'Hãy đi bộ trên vỉa hè.',
  ),
  _curatedWord(
    'crossing',
    'Crossing',
    'Chỗ qua đường',
    'Đường phố',
    'noun',
    'Use the crossing to cross the road.',
    'Hãy dùng chỗ qua đường để sang đường.',
  ),
  _curatedWord(
    'sign',
    'Sign',
    'Biển báo',
    'Đường phố',
    'noun',
    'The sign tells us to stop.',
    'Biển báo cho chúng ta biết phải dừng lại.',
  ),

  _curatedWord(
    'nurse',
    'Nurse',
    'Y tá',
    'Nghề nghiệp',
    'noun',
    'The nurse helps the patient.',
    'Y tá giúp đỡ bệnh nhân.',
  ),
  _curatedWord(
    'farmer',
    'Farmer',
    'Nông dân',
    'Nghề nghiệp',
    'noun',
    'The farmer works in the field.',
    'Nông dân làm việc trên cánh đồng.',
  ),
  _curatedWord(
    'driver',
    'Driver',
    'Tài xế',
    'Nghề nghiệp',
    'noun',
    'The driver stops for children.',
    'Tài xế dừng xe cho trẻ em.',
  ),
  _curatedWord(
    'chef',
    'Chef',
    'Đầu bếp',
    'Nghề nghiệp',
    'noun',
    'The chef cooks a healthy meal.',
    'Đầu bếp nấu một bữa ăn lành mạnh.',
  ),
  _curatedWord(
    'firefighter',
    'Firefighter',
    'Lính cứu hỏa',
    'Nghề nghiệp',
    'noun',
    'The firefighter protects the town.',
    'Lính cứu hỏa bảo vệ thị trấn.',
  ),

  _curatedWord(
    'basketball',
    'Basketball',
    'Bóng rổ',
    'Thể thao',
    'noun',
    'We play basketball after school.',
    'Chúng em chơi bóng rổ sau giờ học.',
  ),
  _curatedWord(
    'tennis',
    'Tennis',
    'Quần vợt',
    'Thể thao',
    'noun',
    'She plays tennis with her friend.',
    'Bạn ấy chơi quần vợt với bạn.',
  ),
  _curatedWord(
    'volleyball',
    'Volleyball',
    'Bóng chuyền',
    'Thể thao',
    'noun',
    'The team practices volleyball.',
    'Đội tập bóng chuyền.',
  ),
  _curatedWord(
    'running',
    'Running',
    'Chạy bộ',
    'Thể thao',
    'noun',
    'Running keeps our bodies strong.',
    'Chạy bộ giúp cơ thể khỏe mạnh.',
  ),
  _curatedWord(
    'cycling',
    'Cycling',
    'Đạp xe',
    'Thể thao',
    'noun',
    'Cycling is fun in the park.',
    'Đạp xe trong công viên rất vui.',
  ),

  _curatedWord(
    'reading',
    'Reading',
    'Đọc sách',
    'Sở thích',
    'noun',
    'Reading is my favorite hobby.',
    'Đọc sách là sở thích yêu thích của em.',
  ),
  _curatedWord(
    'painting',
    'Painting',
    'Vẽ tranh',
    'Sở thích',
    'noun',
    'Painting helps me relax.',
    'Vẽ tranh giúp em thư giãn.',
  ),
  _curatedWord(
    'singing',
    'Singing',
    'Ca hát',
    'Sở thích',
    'noun',
    'Singing makes her happy.',
    'Ca hát làm bạn ấy vui.',
  ),
  _curatedWord(
    'dancing',
    'Dancing',
    'Nhảy múa',
    'Sở thích',
    'noun',
    'Dancing is exciting.',
    'Nhảy múa rất hào hứng.',
  ),
  _curatedWord(
    'cooking',
    'Cooking',
    'Nấu ăn',
    'Sở thích',
    'noun',
    'Cooking with Dad is fun.',
    'Nấu ăn cùng bố rất vui.',
  ),

  _curatedWord(
    'puzzle',
    'Puzzle',
    'Trò ghép hình',
    'Đồ chơi',
    'noun',
    'This puzzle has many pieces.',
    'Trò ghép hình này có nhiều mảnh.',
  ),
  _curatedWord(
    'kite',
    'Kite',
    'Con diều',
    'Đồ chơi',
    'noun',
    'The kite flies high.',
    'Con diều bay cao.',
  ),
  _curatedWord(
    'robot',
    'Robot',
    'Rô-bốt',
    'Đồ chơi',
    'noun',
    'The robot can move its arms.',
    'Rô-bốt có thể cử động tay.',
  ),
  _curatedWord(
    'teddy_bear',
    'Teddy bear',
    'Gấu bông',
    'Đồ chơi',
    'noun',
    'My teddy bear sits on the bed.',
    'Gấu bông của em ngồi trên giường.',
  ),
  _curatedWord(
    'blocks',
    'Blocks',
    'Khối xếp hình',
    'Đồ chơi',
    'noun',
    'Build a tower with the blocks.',
    'Hãy xây một tòa tháp bằng các khối xếp hình.',
  ),

  _curatedWord(
    'drum',
    'Drum',
    'Trống',
    'Nhạc cụ',
    'noun',
    'He plays the drum loudly.',
    'Bạn ấy đánh trống to.',
  ),
  _curatedWord(
    'violin',
    'Violin',
    'Đàn vĩ cầm',
    'Nhạc cụ',
    'noun',
    'The violin has four strings.',
    'Đàn vĩ cầm có bốn dây.',
  ),
  _curatedWord(
    'flute',
    'Flute',
    'Sáo',
    'Nhạc cụ',
    'noun',
    'She plays a quiet tune on the flute.',
    'Bạn ấy thổi một giai điệu nhẹ trên sáo.',
  ),
  _curatedWord(
    'trumpet',
    'Trumpet',
    'Kèn trumpet',
    'Nhạc cụ',
    'noun',
    'The trumpet is bright and loud.',
    'Kèn trumpet sáng bóng và to.',
  ),

  _curatedWord(
    'phone',
    'Phone',
    'Điện thoại',
    'Công nghệ',
    'noun',
    'My phone is on the table.',
    'Điện thoại của em ở trên bàn.',
  ),
  _curatedWord(
    'camera',
    'Camera',
    'Máy ảnh',
    'Công nghệ',
    'noun',
    'The camera takes a clear picture.',
    'Máy ảnh chụp một bức ảnh rõ.',
  ),
  _curatedWord(
    'keyboard',
    'Keyboard',
    'Bàn phím',
    'Công nghệ',
    'noun',
    'Type your name on the keyboard.',
    'Hãy gõ tên trên bàn phím.',
  ),
  _curatedWord(
    'mouse',
    'Mouse',
    'Chuột máy tính',
    'Công nghệ',
    'noun',
    'Move the mouse to the right.',
    'Di chuyển chuột máy tính sang phải.',
  ),
  _curatedWord(
    'screen',
    'Screen',
    'Màn hình',
    'Công nghệ',
    'noun',
    'The picture is on the screen.',
    'Bức tranh ở trên màn hình.',
  ),
  _curatedWord(
    'charger',
    'Charger',
    'Bộ sạc',
    'Công nghệ',
    'noun',
    'The charger is in my bag.',
    'Bộ sạc ở trong túi của em.',
  ),

  _curatedWord(
    'forest',
    'Forest',
    'Khu rừng',
    'Thiên nhiên',
    'noun',
    'Many animals live in the forest.',
    'Nhiều loài vật sống trong rừng.',
  ),
  _curatedWord(
    'lake',
    'Lake',
    'Hồ',
    'Thiên nhiên',
    'noun',
    'The lake is very quiet.',
    'Hồ rất yên tĩnh.',
  ),
  _curatedWord(
    'beach',
    'Beach',
    'Bãi biển',
    'Thiên nhiên',
    'noun',
    'We collect shells on the beach.',
    'Chúng em nhặt vỏ sò trên bãi biển.',
  ),
  _curatedWord(
    'island',
    'Island',
    'Hòn đảo',
    'Thiên nhiên',
    'noun',
    'The island is far from the city.',
    'Hòn đảo ở xa thành phố.',
  ),
  _curatedWord(
    'sky',
    'Sky',
    'Bầu trời',
    'Thiên nhiên',
    'noun',
    'The sky is full of stars.',
    'Bầu trời đầy sao.',
  ),

  _curatedWord(
    'ticket',
    'Ticket',
    'Vé',
    'Du lịch',
    'noun',
    'Keep your ticket safe.',
    'Hãy giữ vé cẩn thận.',
  ),
  _curatedWord(
    'passport',
    'Passport',
    'Hộ chiếu',
    'Du lịch',
    'noun',
    'Put your passport in the bag.',
    'Hãy để hộ chiếu vào túi.',
  ),
  _curatedWord(
    'map',
    'Map',
    'Bản đồ',
    'Du lịch',
    'noun',
    'The map shows the way to the hotel.',
    'Bản đồ chỉ đường đến khách sạn.',
  ),
  _curatedWord(
    'suitcase',
    'Suitcase',
    'Va-li',
    'Du lịch',
    'noun',
    'My suitcase is blue.',
    'Va-li của em màu xanh.',
  ),
  _curatedWord(
    'guide',
    'Guide',
    'Hướng dẫn viên',
    'Du lịch',
    'noun',
    'The guide tells us about the city.',
    'Hướng dẫn viên kể cho chúng em về thành phố.',
  ),
];

/// A bundled editorial starter set for the offline demo. The full release is
/// loaded from the versioned backend catalog; this list must not be presented
/// as the 3,000-word production target until the content report says so.
final catalogWords = <CatalogWord>[
  CatalogWord(
    id: 'abacus',
    english: 'Abacus',
    vietnamese: 'Bàn tính',
    topic: 'Đồ dùng học tập',
    partOfSpeech: 'noun',
    exampleEnglish: 'The abacus helps me count.',
    exampleVietnamese: 'Bàn tính giúp em đếm.',
    source: 'school-objects v1 (Roboflow)',
    sourceUrl:
        'https://universe.roboflow.com/schoolobjectsv1/school-objects-8qfiv',
    sourceLicense: 'CC BY 4.0',
    reviewedBy:
        'automated source/media check; human publication review pending',
    imageUrl: 'assets/catalog/e4/abacus.jpg',
    imageLicense: 'CC BY 4.0',
    imageAttribution: 'school-objects v1, provided by a Roboflow user',
  ),
  CatalogWord(
    id: 'backpack',
    english: 'Backpack',
    vietnamese: 'Ba lô',
    topic: 'Đồ dùng học tập',
    partOfSpeech: 'noun',
    exampleEnglish: 'My books are in my backpack.',
    exampleVietnamese: 'Sách của em ở trong ba lô.',
    source: 'school-objects v1 (Roboflow)',
    sourceUrl:
        'https://universe.roboflow.com/schoolobjectsv1/school-objects-8qfiv',
    sourceLicense: 'CC BY 4.0',
    reviewedBy:
        'automated source/media check; human publication review pending',
    imageUrl: 'assets/catalog/e4/backpack.jpg',
    imageLicense: 'CC BY 4.0',
    imageAttribution: 'school-objects v1, provided by a Roboflow user',
  ),
  CatalogWord(
    id: 'chalk',
    english: 'Chalk',
    vietnamese: 'Phấn',
    topic: 'Đồ dùng học tập',
    partOfSpeech: 'noun',
    exampleEnglish: 'The teacher writes with chalk.',
    exampleVietnamese: 'Cô giáo viết bằng phấn.',
    source: 'school-objects v1 (Roboflow)',
    sourceUrl:
        'https://universe.roboflow.com/schoolobjectsv1/school-objects-8qfiv',
    sourceLicense: 'CC BY 4.0',
    reviewedBy:
        'automated source/media check; human publication review pending',
    imageUrl: 'assets/catalog/e4/chalk.jpg',
    imageLicense: 'CC BY 4.0',
    imageAttribution: 'school-objects v1, provided by a Roboflow user',
  ),
  CatalogWord(
    id: 'chalkboard',
    english: 'Chalkboard',
    vietnamese: 'Bảng phấn',
    topic: 'Đồ dùng học tập',
    partOfSpeech: 'noun',
    exampleEnglish: 'The word is on the chalkboard.',
    exampleVietnamese: 'Từ đó ở trên bảng phấn.',
    source: 'school-objects v1 (Roboflow)',
    sourceUrl:
        'https://universe.roboflow.com/schoolobjectsv1/school-objects-8qfiv',
    sourceLicense: 'CC BY 4.0',
    reviewedBy:
        'automated source/media check; human publication review pending',
    imageUrl: 'assets/catalog/e4/chalkboard.jpg',
    imageLicense: 'CC BY 4.0',
    imageAttribution: 'school-objects v1, provided by a Roboflow user',
  ),
  CatalogWord(
    id: 'crayon',
    english: 'Crayon',
    vietnamese: 'Bút sáp màu',
    topic: 'Đồ dùng học tập',
    partOfSpeech: 'noun',
    exampleEnglish: 'I draw with a blue crayon.',
    exampleVietnamese: 'Em vẽ bằng bút sáp màu xanh.',
    source: 'school-objects v1 (Roboflow)',
    sourceUrl:
        'https://universe.roboflow.com/schoolobjectsv1/school-objects-8qfiv',
    sourceLicense: 'CC BY 4.0',
    reviewedBy:
        'automated source/media check; human publication review pending',
    imageUrl: 'assets/catalog/e4/crayon.jpg',
    imageLicense: 'CC BY 4.0',
    imageAttribution: 'school-objects v1, provided by a Roboflow user',
  ),
  CatalogWord(
    id: 'cup',
    english: 'Cup',
    vietnamese: 'Cốc',
    topic: 'Đồ dùng học tập',
    partOfSpeech: 'noun',
    exampleEnglish: 'There is a cup on the desk.',
    exampleVietnamese: 'Có một cái cốc trên bàn.',
    source: 'school-objects v1 (Roboflow)',
    sourceUrl:
        'https://universe.roboflow.com/schoolobjectsv1/school-objects-8qfiv',
    sourceLicense: 'CC BY 4.0',
    reviewedBy:
        'automated source/media check; human publication review pending',
    imageUrl: 'assets/catalog/e4/cup.jpg',
    imageLicense: 'CC BY 4.0',
    imageAttribution: 'school-objects v1, provided by a Roboflow user',
  ),
  CatalogWord(
    id: 'eraser',
    english: 'Eraser',
    vietnamese: 'Cục tẩy',
    topic: 'Đồ dùng học tập',
    partOfSpeech: 'noun',
    exampleEnglish: 'Use an eraser to remove the mark.',
    exampleVietnamese: 'Dùng cục tẩy để xóa vết.',
    source: 'school-objects v1 (Roboflow)',
    sourceUrl:
        'https://universe.roboflow.com/schoolobjectsv1/school-objects-8qfiv',
    sourceLicense: 'CC BY 4.0',
    reviewedBy:
        'automated source/media check; human publication review pending',
    imageUrl: 'assets/catalog/e4/eraser.jpg',
    imageLicense: 'CC BY 4.0',
    imageAttribution: 'school-objects v1, provided by a Roboflow user',
  ),
  CatalogWord(
    id: 'glue_stick',
    english: 'Glue stick',
    vietnamese: 'Hồ khô',
    topic: 'Đồ dùng học tập',
    partOfSpeech: 'noun',
    exampleEnglish: 'The glue stick is in my pencil case.',
    exampleVietnamese: 'Hồ khô ở trong hộp bút của em.',
    source: 'school-objects v1 (Roboflow)',
    sourceUrl:
        'https://universe.roboflow.com/schoolobjectsv1/school-objects-8qfiv',
    sourceLicense: 'CC BY 4.0',
    reviewedBy:
        'automated source/media check; human publication review pending',
    imageUrl: 'assets/catalog/e4/glue_stick.jpg',
    imageLicense: 'CC BY 4.0',
    imageAttribution: 'school-objects v1, provided by a Roboflow user',
  ),
  CatalogWord(
    id: 'kids_chair',
    english: 'Kids chair',
    vietnamese: 'Ghế trẻ em',
    topic: 'Đồ dùng học tập',
    partOfSpeech: 'noun',
    exampleEnglish: 'The child sits on a small chair.',
    exampleVietnamese: 'Bạn nhỏ ngồi trên một chiếc ghế nhỏ.',
    source: 'school-objects v1 (Roboflow)',
    sourceUrl:
        'https://universe.roboflow.com/schoolobjectsv1/school-objects-8qfiv',
    sourceLicense: 'CC BY 4.0',
    reviewedBy:
        'automated source/media check; human publication review pending',
    imageUrl: 'assets/catalog/e4/kids_chair.jpg',
    imageLicense: 'CC BY 4.0',
    imageAttribution: 'school-objects v1, provided by a Roboflow user',
  ),
  CatalogWord(
    id: 'notebook',
    english: 'Notebook',
    vietnamese: 'Vở',
    topic: 'Đồ dùng học tập',
    partOfSpeech: 'noun',
    exampleEnglish: 'Write the new word in your notebook.',
    exampleVietnamese: 'Hãy viết từ mới vào vở.',
    source: 'school-objects v1 (Roboflow)',
    sourceUrl:
        'https://universe.roboflow.com/schoolobjectsv1/school-objects-8qfiv',
    sourceLicense: 'CC BY 4.0',
    reviewedBy:
        'automated source/media check; human publication review pending',
    imageUrl: 'assets/catalog/e4/notebook.jpg',
    imageLicense: 'CC BY 4.0',
    imageAttribution: 'school-objects v1, provided by a Roboflow user',
  ),
  CatalogWord(
    id: 'paintbrush',
    english: 'Paintbrush',
    vietnamese: 'Cọ vẽ',
    topic: 'Đồ dùng học tập',
    partOfSpeech: 'noun',
    exampleEnglish: 'The paintbrush is wet.',
    exampleVietnamese: 'Cọ vẽ đang ướt.',
    source: 'school-objects v1 (Roboflow)',
    sourceUrl:
        'https://universe.roboflow.com/schoolobjectsv1/school-objects-8qfiv',
    sourceLicense: 'CC BY 4.0',
    reviewedBy:
        'automated source/media check; human publication review pending',
    imageUrl: 'assets/catalog/e4/paintbrush.jpg',
    imageLicense: 'CC BY 4.0',
    imageAttribution: 'school-objects v1, provided by a Roboflow user',
  ),
  CatalogWord(
    id: 'pencil',
    english: 'Pencil',
    vietnamese: 'Bút chì',
    topic: 'Đồ dùng học tập',
    partOfSpeech: 'noun',
    exampleEnglish: 'Please sharpen your pencil.',
    exampleVietnamese: 'Em hãy gọt bút chì.',
    source: 'school-objects v1 (Roboflow)',
    sourceUrl:
        'https://universe.roboflow.com/schoolobjectsv1/school-objects-8qfiv',
    sourceLicense: 'CC BY 4.0',
    reviewedBy:
        'automated source/media check; human publication review pending',
    imageUrl: 'assets/catalog/e4/pencil.jpg',
    imageLicense: 'CC BY 4.0',
    imageAttribution: 'school-objects v1, provided by a Roboflow user',
  ),
  CatalogWord(
    id: 'pencil_sharpener',
    english: 'Pencil sharpener',
    vietnamese: 'Gọt bút chì',
    topic: 'Đồ dùng học tập',
    partOfSpeech: 'noun',
    exampleEnglish: 'The sharpener is beside the pencil.',
    exampleVietnamese: 'Đồ gọt ở cạnh bút chì.',
    source: 'school-objects v1 (Roboflow)',
    sourceUrl:
        'https://universe.roboflow.com/schoolobjectsv1/school-objects-8qfiv',
    sourceLicense: 'CC BY 4.0',
    reviewedBy:
        'automated source/media check; human publication review pending',
    imageUrl: 'assets/catalog/e4/pencil_sharpener.jpg',
    imageLicense: 'CC BY 4.0',
    imageAttribution: 'school-objects v1, provided by a Roboflow user',
  ),
  CatalogWord(
    id: 'ruler',
    english: 'Ruler',
    vietnamese: 'Thước kẻ',
    topic: 'Đồ dùng học tập',
    partOfSpeech: 'noun',
    exampleEnglish: 'Use a ruler to draw a straight line.',
    exampleVietnamese: 'Dùng thước kẻ để vẽ đường thẳng.',
    source: 'school-objects v1 (Roboflow)',
    sourceUrl:
        'https://universe.roboflow.com/schoolobjectsv1/school-objects-8qfiv',
    sourceLicense: 'CC BY 4.0',
    reviewedBy:
        'automated source/media check; human publication review pending',
    imageUrl: 'assets/catalog/e4/ruler.jpg',
    imageLicense: 'CC BY 4.0',
    imageAttribution: 'school-objects v1, provided by a Roboflow user',
  ),
  CatalogWord(
    id: 'scissors',
    english: 'Scissors',
    vietnamese: 'Kéo',
    topic: 'Đồ dùng học tập',
    partOfSpeech: 'noun',
    exampleEnglish: 'Cut the paper with scissors.',
    exampleVietnamese: 'Cắt giấy bằng kéo.',
    source: 'school-objects v1 (Roboflow)',
    sourceUrl:
        'https://universe.roboflow.com/schoolobjectsv1/school-objects-8qfiv',
    sourceLicense: 'CC BY 4.0',
    reviewedBy:
        'automated source/media check; human publication review pending',
    imageUrl: 'assets/catalog/e4/scissors.jpg',
    imageLicense: 'CC BY 4.0',
    imageAttribution: 'school-objects v1, provided by a Roboflow user',
  ),
  CatalogWord(
    id: 'apple',
    english: 'Apple',
    vietnamese: 'Quả táo',
    topic: 'Trái cây',
    partOfSpeech: 'noun',
    exampleEnglish: 'I eat an apple after school.',
    exampleVietnamese: 'Em ăn một quả táo sau giờ học.',
  ),
  CatalogWord(
    id: 'banana',
    english: 'Banana',
    vietnamese: 'Quả chuối',
    topic: 'Trái cây',
    partOfSpeech: 'noun',
    exampleEnglish: 'The banana is yellow.',
    exampleVietnamese: 'Quả chuối màu vàng.',
  ),
  CatalogWord(
    id: 'orange',
    english: 'Orange',
    vietnamese: 'Quả cam',
    topic: 'Trái cây',
    partOfSpeech: 'noun',
    exampleEnglish: 'This orange is sweet.',
    exampleVietnamese: 'Quả cam này ngọt.',
  ),
  CatalogWord(
    id: 'grape',
    english: 'Grape',
    vietnamese: 'Quả nho',
    topic: 'Trái cây',
    partOfSpeech: 'noun',
    exampleEnglish: 'She washes the grapes.',
    exampleVietnamese: 'Bạn ấy rửa nho.',
  ),
  CatalogWord(
    id: 'watermelon',
    english: 'Watermelon',
    vietnamese: 'Dưa hấu',
    topic: 'Trái cây',
    partOfSpeech: 'noun',
    exampleEnglish: 'We share a watermelon.',
    exampleVietnamese: 'Chúng em cùng ăn dưa hấu.',
  ),
  CatalogWord(
    id: 'carrot',
    english: 'Carrot',
    vietnamese: 'Cà rốt',
    topic: 'Rau củ',
    partOfSpeech: 'noun',
    exampleEnglish: 'The rabbit likes a carrot.',
    exampleVietnamese: 'Con thỏ thích cà rốt.',
  ),
  CatalogWord(
    id: 'potato',
    english: 'Potato',
    vietnamese: 'Khoai tây',
    topic: 'Rau củ',
    partOfSpeech: 'noun',
    exampleEnglish: 'The potato is in the basket.',
    exampleVietnamese: 'Củ khoai tây ở trong giỏ.',
  ),
  CatalogWord(
    id: 'tomato',
    english: 'Tomato',
    vietnamese: 'Cà chua',
    topic: 'Rau củ',
    partOfSpeech: 'noun',
    exampleEnglish: 'The tomato is red.',
    exampleVietnamese: 'Quả cà chua màu đỏ.',
  ),
  CatalogWord(
    id: 'cat',
    english: 'Cat',
    vietnamese: 'Con mèo',
    topic: 'Động vật',
    partOfSpeech: 'noun',
    exampleEnglish: 'The cat is sleeping.',
    exampleVietnamese: 'Con mèo đang ngủ.',
  ),
  CatalogWord(
    id: 'dog',
    english: 'Dog',
    vietnamese: 'Con chó',
    topic: 'Động vật',
    partOfSpeech: 'noun',
    exampleEnglish: 'The dog runs fast.',
    exampleVietnamese: 'Con chó chạy nhanh.',
  ),
  CatalogWord(
    id: 'rabbit',
    english: 'Rabbit',
    vietnamese: 'Con thỏ',
    topic: 'Động vật',
    partOfSpeech: 'noun',
    exampleEnglish: 'The rabbit has long ears.',
    exampleVietnamese: 'Con thỏ có đôi tai dài.',
  ),
  CatalogWord(
    id: 'bird',
    english: 'Bird',
    vietnamese: 'Con chim',
    topic: 'Động vật',
    partOfSpeech: 'noun',
    exampleEnglish: 'A bird is in the tree.',
    exampleVietnamese: 'Một con chim ở trên cây.',
  ),
  CatalogWord(
    id: 'fish',
    english: 'Fish',
    vietnamese: 'Con cá',
    topic: 'Động vật',
    partOfSpeech: 'noun',
    exampleEnglish: 'The fish swims in the pond.',
    exampleVietnamese: 'Con cá bơi trong ao.',
  ),
  CatalogWord(
    id: 'mother',
    english: 'Mother',
    vietnamese: 'Mẹ',
    topic: 'Gia đình',
    partOfSpeech: 'noun',
    exampleEnglish: 'My mother reads with me.',
    exampleVietnamese: 'Mẹ đọc sách cùng em.',
  ),
  CatalogWord(
    id: 'father',
    english: 'Father',
    vietnamese: 'Bố',
    topic: 'Gia đình',
    partOfSpeech: 'noun',
    exampleEnglish: 'My father cooks dinner.',
    exampleVietnamese: 'Bố nấu bữa tối.',
  ),
  CatalogWord(
    id: 'sister',
    english: 'Sister',
    vietnamese: 'Chị/em gái',
    topic: 'Gia đình',
    partOfSpeech: 'noun',
    exampleEnglish: 'My sister draws a picture.',
    exampleVietnamese: 'Chị em vẽ một bức tranh.',
  ),
  CatalogWord(
    id: 'brother',
    english: 'Brother',
    vietnamese: 'Anh/em trai',
    topic: 'Gia đình',
    partOfSpeech: 'noun',
    exampleEnglish: 'My brother plays outside.',
    exampleVietnamese: 'Anh em chơi ở bên ngoài.',
  ),
  CatalogWord(
    id: 'home',
    english: 'Home',
    vietnamese: 'Nhà',
    topic: 'Địa điểm',
    partOfSpeech: 'noun',
    exampleEnglish: 'We walk home together.',
    exampleVietnamese: 'Chúng em cùng đi bộ về nhà.',
  ),
  CatalogWord(
    id: 'school',
    english: 'School',
    vietnamese: 'Trường học',
    topic: 'Địa điểm',
    partOfSpeech: 'noun',
    exampleEnglish: 'Our school has a library.',
    exampleVietnamese: 'Trường em có một thư viện.',
  ),
  CatalogWord(
    id: 'library',
    english: 'Library',
    vietnamese: 'Thư viện',
    topic: 'Địa điểm',
    partOfSpeech: 'noun',
    exampleEnglish: 'I borrow a book from the library.',
    exampleVietnamese: 'Em mượn một quyển sách từ thư viện.',
  ),
  CatalogWord(
    id: 'classroom',
    english: 'Classroom',
    vietnamese: 'Lớp học',
    topic: 'Địa điểm',
    partOfSpeech: 'noun',
    exampleEnglish: 'The classroom is bright.',
    exampleVietnamese: 'Lớp học sáng sủa.',
  ),
  CatalogWord(
    id: 'red',
    english: 'Red',
    vietnamese: 'Màu đỏ',
    topic: 'Màu sắc',
    partOfSpeech: 'adjective',
    exampleEnglish: 'The red ball is on the floor.',
    exampleVietnamese: 'Quả bóng đỏ ở trên sàn.',
  ),
  CatalogWord(
    id: 'blue',
    english: 'Blue',
    vietnamese: 'Màu xanh dương',
    topic: 'Màu sắc',
    partOfSpeech: 'adjective',
    exampleEnglish: 'The sky is blue.',
    exampleVietnamese: 'Bầu trời màu xanh dương.',
  ),
  CatalogWord(
    id: 'green',
    english: 'Green',
    vietnamese: 'Màu xanh lá',
    topic: 'Màu sắc',
    partOfSpeech: 'adjective',
    exampleEnglish: 'The leaves are green.',
    exampleVietnamese: 'Lá cây màu xanh lá.',
  ),
  CatalogWord(
    id: 'yellow',
    english: 'Yellow',
    vietnamese: 'Màu vàng',
    topic: 'Màu sắc',
    partOfSpeech: 'adjective',
    exampleEnglish: 'The sun is yellow in the picture.',
    exampleVietnamese: 'Mặt trời màu vàng trong bức tranh.',
  ),
  CatalogWord(
    id: 'run',
    english: 'Run',
    vietnamese: 'Chạy',
    topic: 'Hành động',
    partOfSpeech: 'verb',
    exampleEnglish: 'I run in the playground.',
    exampleVietnamese: 'Em chạy ở sân chơi.',
  ),
  CatalogWord(
    id: 'read',
    english: 'Read',
    vietnamese: 'Đọc',
    topic: 'Hành động',
    partOfSpeech: 'verb',
    exampleEnglish: 'We read a short story.',
    exampleVietnamese: 'Chúng em đọc một câu chuyện ngắn.',
  ),
  CatalogWord(
    id: 'write',
    english: 'Write',
    vietnamese: 'Viết',
    topic: 'Hành động',
    partOfSpeech: 'verb',
    exampleEnglish: 'Please write your name.',
    exampleVietnamese: 'Hãy viết tên của em.',
  ),
  CatalogWord(
    id: 'listen',
    english: 'Listen',
    vietnamese: 'Nghe',
    topic: 'Hành động',
    partOfSpeech: 'verb',
    exampleEnglish: 'Listen to the teacher.',
    exampleVietnamese: 'Hãy nghe cô giáo.',
  ),
  CatalogWord(
    id: 'happy',
    english: 'Happy',
    vietnamese: 'Vui vẻ',
    topic: 'Cảm xúc',
    partOfSpeech: 'adjective',
    exampleEnglish: 'I feel happy today.',
    exampleVietnamese: 'Hôm nay em cảm thấy vui.',
  ),
  CatalogWord(
    id: 'tired',
    english: 'Tired',
    vietnamese: 'Mệt',
    topic: 'Cảm xúc',
    partOfSpeech: 'adjective',
    exampleEnglish: 'He is tired after the game.',
    exampleVietnamese: 'Bạn ấy mệt sau trận chơi.',
  ),
  ..._expandedStarterWords,
  ..._curatedStarterExpansion,
];

const catalogTopics = <String>[
  'Đồ dùng học tập',
  'Trái cây',
  'Rau củ',
  'Động vật',
  'Gia đình',
  'Địa điểm',
  'Màu sắc',
  'Hành động',
  'Cảm xúc',
  'Số đếm',
  'Hình dạng',
  'Cơ thể',
  'Hành động hằng ngày',
  'Đồ trong nhà',
  'Phòng bếp',
  'Phòng ngủ',
  'Quần áo',
  'Giày và phụ kiện',
  'Món ăn',
  'Đồ uống',
  'Thú nuôi',
  'Động vật hoang dã',
  'Chim',
  'Sinh vật biển',
  'Côn trùng',
  'Cây và hoa',
  'Thời tiết',
  'Mùa',
  'Thời gian',
  'Ngày và tháng',
  'Phương tiện',
  'Đường phố',
  'Nghề nghiệp',
  'Thể thao',
  'Sở thích',
  'Đồ chơi',
  'Nhạc cụ',
  'Công nghệ',
  'Thiên nhiên',
  'Du lịch',
];
